### ISSUE TITLE
Formatting in messages

### ISSUE THREAD

**Issue by reicruz** [ibm-cloud-solutions/hubot-ibmcloud-nlc#52]
Some of the messages are using `` for highlighting words instead of using **.

**Comment by jlpadilla** [comment]
While you are updating it, can you change this statement

> I have `7` new approved training statement(s).

to be **bold** instead of `code`?

>  I have **7** new approved training statement(s).

**Comment by reicruz** [comment]
@jlpadilla 

Will do!
