### ISSUE TITLE
Don't process NLC for commands from other bots

### ISSUE THREAD

**Issue by jlpadilla** [ibm-cloud-solutions/hubot-ibmcloud-nlc#57]
When multiple bots are on the same channel they can go on an infinite conversation.  To avoid this filter messages coming from another bot.

**Comment by CiaranHannigan** [comment]
Seems we are also responding to people if they mention cloudbot in a message (without the `@`)

From dW Open Slack,

"is there a tutorial/blog or ? that guides a user through the deployment and configuration of **cloudbot**?  I’m finding bits here and there, but haven’t found the golden tutorial yet" (emphasis is mine)

**Comment by jlpadilla** [comment]
@CiaranHannigan I thought the `@` was Slack specific syntax, but I could easily be wrong.

Not matching the `@` was very likely the reason why the problem started, after that they were just mentioning each other's names with the reply.
