### ISSUE TITLE
filter hubot responses when NLC is disabled

### ISSUE THREAD

**Issue by ngawor** [ibm-cloud-solutions/hubot-ibmcloud-nlc#58]
Basically we need to add `res.message.user.name !== 'hubot' &&`  here:https://github.com/ibm-cloud-solutions/hubot-ibmcloud-nlc/blob/master/src/scripts/nlc.catchall.js#L150

**Comment by jlpadilla** [comment]
@CiaranHannigan this is related to #57.  Please make sure the solution you are working on covers both paths.

**Comment by CiaranHannigan** [comment]
got it, will make sure that is included in my solution
