### ISSUE TITLE
Direct messaging the bot with Natural Language doesn't get a response.

### ISSUE THREAD

**Issue by clanzen** [ibm-cloud-solutions/hubot-ibmcloud-nlc#68]
I found this during testing today, so I believe today's deployment may have broken something.  It works in a regular chat when you're addressing the bot.  But in a DM, when I tried something like "I want to deploy my github application", I got no response.

Oddly, if I address the bot, I get other results, but they aren’t right.

```
‘@ibmcloudbot I want to deploy my github application” results in 
[High confidence] Will process top class [github.deploy]
Deploying `@ibmcloudbot` from master branch of @ibmcloudbot.
Obtaining repository data for application `@ibmcloudbot`.
A deployment error occurred for app `@ibmcloudbot`: Invalid or unsupported zip format. No END header found.
```

It clearly picked up the right command, but then incorrectly guessed the args.  I’m mostly concerned that it didn’t respond with the initial command, when I didn’t address it (considering it is a direct message)

**Comment by CiaranHannigan** [comment]
I found the issue, and what happened was my fix exposed that the condition check for private messages will always return `false`. The way private messaging was working was based on the fact that the check for the bot name in the message was returning true. Now that my check requires that there be a `@` attached to the bot name broke exposed it.

I will be using this as how we will check for private messages
https://github.com/slackhq/hubot-slack/blob/master/src/bot.coffee#L132
