### ISSUE TITLE
troubleshooting info needed in readme

### ISSUE THREAD

**Issue by aeweidne** [ibm-cloud-solutions/hubot-ibmcloud-nlc#8]
While trying to NLC-enable a bot, I hit some issues and didn't know where to go. It would have been helpful to see a troubleshooting guide in the readme, or something similar, where I might find my symptom and and the proper action to take. Issues I ran into:
- [x] From where I started the bot, the console printed: "WARNING ibmcloud-auth.js: The 'context' object doesn't contain a 'commandId' or 'listener.options_id' key. Unrecognized commands are authorized."
- [x] From where I started the bot, the console printed: "WARNING Expected /Users/craiglanzen/Documents/workspace/hubot-ibmcloud-service-management/node_modules/@ibm/hubot-ibmcloud-auth/src/scripts/env to assign a function to module.exports, got object"
- [x] From where the I started the bot, the console printed: "ERROR Error while training a new classifier Error creating classifier:{}" While I did see the message in slack that training had begun, I never got the "finished training message" that others get when it works. I didn't know if I should just keep waiting longer or what to do. It would be ideal if some periodic message could come out informing the user that training was still going on. Although I'm not sure of the frequency. That could be discussed. If training fails, as I "think" it did in my scenario, it would be appropriate to have a message print out to that affect. I was stuck waiting for 20-30 minutes wondering if it was still training or not, before giving up and killing the bot off. I'm actually still trying to figure out what's wrong ... and maybe nothing is wrong.

**Comment by jlpadilla** [comment]
Problem (2) fixed with https://github.com/ibm-cloud-solutions/hubot-ibmcloud-auth/issues/13

Problem (3) fixed via #36 and #41 .  Also, additional logging was added with https://github.com/ibm-cloud-solutions/hubot-ibmcloud-cognitive-lib/pull/28

**Comment by jlpadilla** [comment]
Problem (1)  Created issue https://github.com/ibm-cloud-solutions/hubot-ibmcloud-auth/issues/15

**Comment by jlpadilla** [comment]
All the issues are either resolved or have corresponding issues opened.
